### ISSUE TITLE
PyCQA logo

### ISSUE THREAD

**Issue by jhermann** [PyCQA/meta#1]
See the mailing list discussion. To get some creativity + discussion flowing, here's a rough idea…

![pycqa.png](http://i.imgur.com/lE6ScB6.png)

**Comment by Nurdok** [comment]
My Photoshop skills are lacking, but my suggestion: "PyCQA" where the Q is a maginfying glass (as in, looking for bugs, violations, etc.)

**Comment by jhermann** [comment]
![pycqa2](http://i.imgur.com/bB8CMgi.png)

**Comment by sigmavirus24** [comment]
Hey @jhermann please refer to the [PSF's Trademark Usage Policy](https://www.python.org/psf/trademarks/) (specifically the "Derived Logos" section). Tl;dr, we're better off not using the Python logo like this as it is most likely trademark infringement. Then again IANAL, so if we decide on a logo like this, we should run it past the Tradmarks Committee.

(To be very clear, I think the first one here is very certainly a violation of the trademark, the second one, probably not.)

**Comment by sigmavirus24** [comment]
Also, @jhermann thanks for putting effort into these logos and starting this issue for us! You're awesome! :metal:

**Comment by IanLee1521** [comment]
IANAL so I won't comment on the Trademark issues, but I like what you've come up with @jhermann ! In the second one with the magnifying glass, I feel like the "py" clashes a bit style-wise with the "cqa" due to the different font weight, but I'm not a graphic designer, so take that with a grain of salt.

**Comment by sigmavirus24** [comment]
Also, as for the bit about derived logos, note that [Pillow](/python-pillow/Pillow)'s logo was audited and approved by the PSF Trademark Committee (if you're looking for inspiration):

![Pillow's Logo](https://python-pillow.github.io/images/pillow-logo.png)

That said, I feel like using the Python logo may make yet more people feel there is an association with the PSF. I'd like to avoid that if possible.

**Comment by Nurdok** [comment]
I don't have photoshop installed at the moment, but I imagined something like this (I did this in Paint, it's just to show the concept):
![pycqa](https://cloud.githubusercontent.com/assets/80665/12795643/99fe543e-cac3-11e5-8dd8-c7601533ba14.png)

**Comment by sigmavirus24** [comment]
Where the Q is a magnifying glass? I like that. It's a lot like @jhermann's second logo (sans PSF trademarked Python logo). 

I wonder if someone clever could work a snake in there or get some lint (or a snow flake, or both) under the microscope.

FWIW, The PyPA's logo is on their [organization](https://github.com/pypa) page but I think they're more closely affiliated with the PSF. The PyCA does not yet have a logo: https://github.com/pyca

**Comment by IanLee1521** [comment]
I also like @Nurdok 's suggestion. Any objections to using that for the PyCQA logo? In my head if we decided to update it later, it shouldn't be difficult, but maybe I'm missing something.  And then we can have something other than space invaders as the [org logo](https://github.com/PyCQA). ;)

**Comment by Nurdok** [comment]
It would be nice if someone with some Photoshop chops will make this design
idea prettier, though.

**Comment by sigmavirus24** [comment]
> It would be nice if someone with some Photoshop chops will make this design idea prettier, though.

We could maybe look at hiring someone to do this. I have some ex-coworkers who might be interested.

**Comment by sigmavirus24** [comment]
I think @glynnis is going to take on making a logo for us. :-D

**Comment by glynnis** [comment]
Hey y'all (cc/ @sigmavirus24) -- finally got to take a stab tonight. I didn't go with the magnifying glass idea because I think that kind of imagery is often associated with searching (a la Google), which I didn't think was the most accurate association for the project.

Here's what I came up with. I focused more on the "style" side of things and wanted to come up with a classy look and feel that evokes quality. Both versions have a pop of color that I think contributes to this, and the "CQA" letters are made by reducing their forms to shapes, with a little code node on the end for good measure (and to set the logo apart from something in the more "modern art" or "print making" realm of logotypes).

### Option 1
![pycqa1](https://cloud.githubusercontent.com/assets/1529366/14007964/d2efc6a4-f149-11e5-9146-ab5a68de13fb.png)
I love the glyphs on this one -- I think it speaks more to the "style" and "elegance" or "cleanliness" side of code styling and linting. It has a bespoke element to it which I like, but full disclosure I'm a calligrapher and I go weak at the knees for a good swash, so I'm probably biased. In the "con" column for this one is that the thinner strokes of the letters may be less legible at very small sizes (like in avatars or in the < 10pt font range).

### Option 2
![pycqa2](https://cloud.githubusercontent.com/assets/1529366/14007965/d2f25450-f149-11e5-903c-de2a0249e934.png)
This one isn't as elegant or flow-y with the different font choice, but the "Py" does evoke more of a computery/code feel, and makes the "CQA" letterforms feel more like planetary/scientific diagram type shapes (maybe because the "Py" would fit in with the NASA logo?). This would stay legible at smaller sizes if that kind of thing is important, and might read more quickly as "this is a computery code-y logo" (especially with the green node at the end). I think altogether that makes a strong case for this version, but overall I don't think it looks as nice (says the hobbyist calligrapher).

Let me know what you think! I have the vector files and can assemble some alternate sizes, pass of hex or rgb color codes, etc., once you decide which you want to go with.

:heart: :sparkles:

**Comment by The-Compiler** [comment]
Whoa, those look great - I love the idea with the shapes as letters! :+1: 

After seeing the first one, I immediately thought it might be problematic at small sizes too. Personally, I love seeing calligraphy with paper and ink, but I always feel it comes off as "cheap" when using it in a logo like this - so I'd prefer the second choice.

**Comment by IanLee1521** [comment]
Those are awesome @glynnis !

I think I'm also leaning towards option 2, especially when I think that one of the first uses we're thinking of is a avatar version for the GitHub organization ([GitHub recommends 500x500](https://help.github.com/articles/how-do-i-set-up-my-profile-picture/) max there).

**Comment by sigmavirus24** [comment]
I like the first one so much better actually

**Comment by sigmavirus24** [comment]
I do understand the concern about smaller sizes though. I wonder if we need to use the full logo for the GitHub organization. I feel like this logo would make for a much more beautiful sticker too.

**Comment by groteworld** [comment]
I agree with @sigmavirus24. It's a little more confusing, but just @glynnis' "CQA" be the shortened avatar/sticker version and then Option 1 be the official, full-length, website/documentation/letter heading version.

Both are great though.

**Comment by sigmavirus24** [comment]
Also, I'm going to remind people that the images above are still @glynnis's copyright (just as the others are copyrighted by the people who posted them).

**Comment by IanLee1521** [comment]
I guess I hadn't considered trimming it to just the "CQA" part for that avatar. That sounds like a fine solution, and then using the more stylized option 1 from @glynnis

**Comment by glynnis** [comment]
### Final logo
![pycqa1-01](https://cloud.githubusercontent.com/assets/1529366/14049238/eee93410-f281-11e5-8100-c4e401ad8a5c.jpg)

### Square version
![pycqa1-02](https://cloud.githubusercontent.com/assets/1529366/14049239/eeebc27a-f281-11e5-8141-a4635886190c.jpg)

### Color palette + codes
![pycqa1-03](https://cloud.githubusercontent.com/assets/1529366/14049240/eeec9c4a-f281-11e5-9395-2e392339b1b9.jpg)

I also have an .AI file for all of the above if y'all need a higher res or vector version of any of these.

**Comment by sigmavirus24** [comment]
Thanks again @glynnis!
