### ISSUE TITLE
End of Python2 support

### ISSUE THREAD

**Issue by pgjones** [PyCQA/meta#19]
Does the PyCQA have a date and process to end Python2 support? I think it might be helpful if it was consistent across the PyCQA.

**Comment by sigmavirus24** [comment]
We don't presently have one, but we can *certainly* discuss it and try to reach consensus.

Over on [twine](/pypa/twine) I've recently mentioned that [I want to drop](https://github.com/pypa/twine/issues/181#issuecomment-230772066) support *before* Python 2's actual End of Life.

I don't know what other projects here think, but the way I envision this working is let's say we have a Project that is on version 12.2.3 and they want to release their next version to drop support for Python 2. Most projects use semantic versioning, or something approximating that, so **I** would do something like:

- Release 12.3.0 as the final version supporting Python 2 with a warning for people running it on Python 2.
- Support *critical* bug fixes for 12.3.x for 1 year.
- At approximately the same time, release 13.0.0 which drops all official support for Python 2. I wouldn't necessary change the code-base to *make* it break but any technical debt (dependencies that are Python 3 backports) would be removed from the packaging metadata for simplicity.

I hope that makes sense. That's also just my idea of how things would work for *my* projects. Y'all can do whatever you want unless you all want to come to consensus.

I would hope that we don't stop projects from dropping support before others though (if they want).

**Comment by sigmavirus24** [comment]
All of that said, I think most projects should be dropping support for Python 2.6 and 3.2. Pip is working towards dropping support for those projects so you may as well follow suite. (Flake8 3.0 will not support 2.6 as a matter of us not wanting to support something that is no longer supported by the upstream CPython core developers and has not been supported for several years.)

Flake8 is further of the opinion that if people really need Python 2.6 support, they will either pay us or pay someone else to provide that support for Flake8 3. See also: [Stop Supporting Python 2.6 (For Free)](http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html) by the excellent @ncoghlan

**Comment by PCManticore** [comment]
For Pylint, this is probably going to happen when Python 3.7 is going to be released, partially because of PEP 479 (https://www.python.org/dev/peps/pep-0479/). We were relying on this feature for astroid and now we have some ugly hacks to support the old behavior, which I can't wait to get rid of. We will do a major release before then (probably 5.0 by that point), which will be the last one to support Python 2, providing bug fixes for a couple of months afterwards.

This is in line with what we did for Python 2.6, we dropped support for it two years ago, with Pylint 1.3.0, for which we had a couple of patch releases for a little while.

**Comment by glyph** [comment]
Dropping Python 2 entirely seems premature given the lack of a robust PyPy+Python 3 runtime.  For me, this is the real gating factor on production use of Python 3.

**Comment by ncoghlan** [comment]
In the case of PyCQA, existing projects running on Python 2 seeing their tooling go into stasis around the 3.7 release time frame (tentatively mid-2018) shouldn't be a major problem - as with Python itself, it takes time for newer versions to build up sufficient additional features for folks to really start to feel the pain of running older versions, so it would be quite strange for a team in 2020 to be OK with using a 10 year old version of the language runtime definition but get upset about using a 2 year old version of their QA tools.

**Comment by sigmavirus24** [comment]
> Dropping Python 2 entirely seems premature given the lack of a robust PyPy+Python 3 runtime. For me, this is the real gating factor on production use of Python 3.

I guess that's the difference. pylint, flake8, etc. aren't really used in production anywhere. They're developer tools.

If they are being used in production, then ostensibly those companies can afford to help sustain the tooling on Python 2.

I neither enjoy writing code that works on Python 2, nor do I want to continue to do it. If someone wants me to write that code and they want me to maintain Python 2 support then they can pay me to do it. If they don't want to pay me to do it, they can pay @ncoghlan to do it. ;)

**Comment by Nurdok** [comment]
I intend for pydocstyle to drop support for Python 2.6 in the next major release, although I have no estimation as to when that's going to happen. Since my workplace still uses Python 2.7, I don't indent to stop supporting it in the next year, but do intend to drop support before 2020 (Python 2's EOL). Dropping support mid-2018 (like @ncoghlan suggested) seems totally reasonable to me.

**Comment by pgjones** [comment]
Flake8-import-order will also drop Python2.6 in the next release and Python3.2 is already not supported. I agree with the suggested final Python2 supported release when Python3.7 is released although I think Flake8-import-order should follow Flake8.

**Comment by Nurdok** [comment]
Almost a year has passed since this discussion and I'm getting more and more inclined to drop support for Python 2.7 soon. Does anyone have plans to drop Python 2.7 support in the near future?

**Comment by sigmavirus24** [comment]
@Nurdok I'd be on board with Flake8 dropping 2.7 support for 2018

**Comment by Nurdok** [comment]
As in, beginning of 2018?

**Comment by PCManticore** [comment]
For pylint, we're planning to drop support once 3.7 is released.

**Comment by Nurdok** [comment]
According to [PEP-537](https://www.python.org/dev/peps/pep-0537/), this means at least mid-2018:

> ### 3.7.0 schedule
> Expected (preliminary):
> 
> 3.7 development begins: 2016-09-12
> 3.7.0 alpha 1: 2017-09-11
> 3.7.0 alpha 2: 2017-10-16
> 3.7.0 alpha 3: 2017-11-13
> 3.7.0 alpha 4: 2017-12-18
> 3.7.0 beta 1: 2018-01-29 (No new features beyond this point.)
> 3.7.0 beta 2: 2018-02-26
> 3.7.0 beta 3: 2018-03-26
> 3.7.0 beta 4: 2018-04-30
> 3.7.0 candidate 1: 2018-05-21
> 3.7.0 candidate 2: 2018-06-04 (if necessary)
> 3.7.0 final: 2018-06-1

**Comment by sigmavirus24** [comment]
June 2018 sounds like as good a month as ever to target that. I'm not particular about when in 2018 and I doubt I'll hold myself to any particular schedule to be honest.

**Comment by hugovk** [comment]
Numpy has already dropped 2.6. From January 1 to December 31, 2019, they plan only bug fixes for 2.7, and then dropping 2.7 on January 1, 2020. 

https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst

See also http://www.python3statement.org/

**Comment by sigmavirus24** [comment]
@hugovk thanks for including that. We're collectively hoping to drop 2.7 long before that and I think most projects already dropped support for 2.6.

**Comment by ambv** [comment]
### Drop runtime Python 2 support but keep support for analyzing Python 2 code
PyCQA tooling is helping people migrate from Python 2 to Python 3. A lot of them will be doing that late in the process, likely long after the official Jan 1 2020 Python 2 EOL. We need to support those people.

What I'm doing with https://github.com/ambv/black/ is to not support *running my tool with Python 2.7* but I do support *acting with my tool on a Python 2.7 codebase*. This is also the case for Mypy and this is what I think we should be doing with Flake8 et al. going forward.

With this in mind, we can drop Python 2 support sooner rather than later. When you do, consider requiring Python 3.6+ straight from the get go. Dictionaries are faster and f-strings are both faster and easier to read. Both of which is important for our use cases.

### A bit of controversy
Since people have access to "modernize", "futurize", and so on, we really don't need to accept every Python 2 syntax wart. I increasingly expect Python 2 code to be "straddling code", e.g. code that at least doesn't use deprecated Python 2-only syntax. Biggest offenders: print statement, exec statement, tuple unpacking in function signatures, except with comma, backticks. All of those have trivial fixes.

**Comment by sigmavirus24** [comment]
So how does one tokenize and/or build an AST for Python 2 from a Python 3 runtime? Is the only way to use a CST like lib2to3?

**Comment by ambv** [comment]
Somebody could build an AST on top of Parso or lib2to3 but currently I don't know of any such project so CST it is. There are third-party ASTs like the ones that pylint is using which might implement this. I don't know them in much depth and I've been rather cautious not to recommend them since they tend to either lag behind latest Python 3 support or have weird edge cases where they either reject valid syntax or accept invalid syntax.

**Comment by PCManticore** [comment]
Chiming in here just to mention that pylint's AST library (https://github.com/PyCQA/astroid) is mostly a wrapper on top of the builtin ast module. As far as I know, it doesn't reject any valid syntax of Python, the only situation where that might occur is rejecting new syntax for Python 3 versions it doesn't yet support (e.g currently it doesn't support Python 3.7, but it will once that's released).

Regarding the support for analyzing Python 2 code, we're probably going to do that for pylint, but as @ambv mentioned, given the fact that we're running on top of the builtin ast module, some Python 2 code might be rejected due to Python 2 only syntax.

**Comment by ncoghlan** [comment]
Even lib2to3 is affected by the "doesn't accept all new Python 3 features" problem, since it uses a hybrid grammar file that bridges Python 2.7 and earlier versions of Python 3.x.

So I think it would be eminently reasonable to only support the subset of Python 2.7 that passes `pylint --py3k` (i.e. using the Py3 ast module to analyse the compatible subset of Python 2.7)

If there turns out to be significant demand for ongoing analysis of never-to-be-modernised code bases, then that would presumably end up being a problem for commercial vendors to worry about (and I expect they'll attempt to solve it by way of "Here are old versions of source code analysis tools, to analyse your old source code").

(Mentioning for the record: https://github.com/spranesh/Redhawk is/was an interestingly ambitious project to allow multi-version source code analysis, but it suffers heavily from the problem @ambv mentioned of needing to be manually kept up to date with language changes)

**Comment by ambv** [comment]
> Even lib2to3 is affected by the "doesn't accept all new Python 3 features" problem, since it uses a hybrid grammar file that bridges Python 2.7 and earlier versions of Python 3.x.

This is misleading. lib2to3 in Python 3.7 doesn't support all the grammar features of Python 3.7 due to omissions and neglect (a third tokenizer and second grammar in the stdlib get easily forgotten during changes). There's nothing inherently impossible to make it work with totally modern code. I was fixing stuff I found myself and I'm sure by 3.7.0 we will have feature parity. Yes, we do have a separate grammar variant in lib2to3 for the print statement vs. the print function. That means you can choose which one you want.

Missing features now include:
- exec function (easily worked around at runtime however);
- async generator expressions are wrongly disallowed in regular functions (creating one should be fine as long as you don't try to iterate over it);
- arbitrary expression unpacking (like `f(*[] if rule else {})`);
- Unicode identifiers.

If you know any others, create an issue on BPO and assign to me.

But my point is, a hybrid grammar doesn't make it impossible to support all the features.

**Comment by ambv** [comment]
@Nurdok, note that 3.4.10, the last release of Python 3.4, is planned for March 2019. So you might want to drop 3.4 at the same time :-)

**Comment by graingert** [comment]
Modernize now requires python ~=3.6

https://github.com/PyCQA/modernize/blob/master/setup.cfg#L23

**Comment by samj1912** [comment]
We also recently dropped support for py3.5 and less in pydocstyle https://github.com/PyCQA/pydocstyle/issues/508

**Comment by sigmavirus24** [comment]
I think everything is off Py2 at this point. Going to close this
