### ISSUE TITLE
Reserving base ids for pylint plugins

### ISSUE THREAD

**Issue by federicobond** [PyCQA/meta#27]
Pylint defines a number range of base ids for messages emitted by its plugins. Is there a way to coordinate and reserve some of these numbers so that tool authors can be more confident that the message ids will not clash?

**Comment by sigmavirus24** [comment]
@federicobond which tool authors are you thinking of here? I think managing a registry like this would be difficult, but it's something that comes up a lot at least with Flake8.

**Comment by federicobond** [comment]
Pylint plug-in developers. I think just listing the base ids used by some popular pylint plugins and letting users submit pull requests to that list would be enough.

**Comment by sigmavirus24** [comment]
Then this sounds not like a meta discussion for all of the projects in the organization, but just something for the pylint repository. I'd suggest that to get actual traction from this that you bring this to the pylint folks directly, either through their bug tracker or the code-quality mailing list.

**Comment by The-Compiler** [comment]
This makes me wonder though: Wouldn't it be better if all projects just used names instead of IDs? pylint is halfway there (it uses the names in a lot of places instead of IDs, but not everywhere...).

That'd make config files much more readable (`ignore = unused-import` vs. `ignore = F401`), and for most cases, nicely solves the collision issue.

**Comment by federicobond** [comment]
Sure! But AFAIK you have to define both a name and ID right now, and IDs must be unique.

@sigmavirus24 I will open a ticket to Pylint then. Thank you for your input.
